### ISSUE TITLE
SpawnPoint для отдела Экспедиций 

### ISSUE THREAD

**Issue by 778b** [778b/starfort-station-14#13]
**Краткое описание:**
Добавить прототипы спавн поинтов для профессий отдела экспедиций,
Примеры прототипов можно найти Resources\Prototypes\Entities\Markers\Spawners\jobs.yml
id родителя у них SpawnPointJobBase

![image](https://user-images.githubusercontent.com/33431126/230766093-a4548f95-ebe0-4fc5-b536-a330ab028596.png)

**Comment by fedKotikeD** [comment]
тоже сделаю. Попробую...
