### ISSUE TITLE
Спавнеры ксеносов

### ISSUE THREAD

**Issue by 778b** [778b/starfort-station-14#24]
**Краткое описание:**
Щас существуют только спавнеры ксеносов которые спавнят раз в несколько минут, надо сделать спавнер одиночный, как пример id: SpawnMobFoxRenault, спавнер лисы. Так же было бы круто запилить спавнер рандомного ксеноса, но это уже смешарикам.
Итого надо сделать 3-5 спавнера для каждого ксеноса и один для королевы.

**Comment by kzhanik** [comment]
Ура мое

**Comment by kzhanik** [comment]
Нет не моё
