### ISSUE TITLE
Добавить цвет отдела Экспедиций в палитру

### ISSUE THREAD

**Issue by 778b** [778b/starfort-station-14#9]
##Краткое описание:
Нужно добавить цвет отдела в палитру, HEX цвета #00836e
Resources\Prototypes\Palettes\departmental.yml

RGB: 
![image](https://user-images.githubusercontent.com/33431126/230765242-0dfaba4d-22a4-4cc4-8b5e-697aa469a5e7.png)

![image](https://user-images.githubusercontent.com/33431126/230765111-1d4f8ccf-da9f-431c-b3fe-43f85bdffcb5.png)

**Comment by fedKotikeD** [comment]
Я попробую сделать, но я не смешарик так что не моментально будет готово

**Comment by MetalSage** [comment]
``- type: palette
  id: Departmental
  name: Departmental
  colors:
    command: "#334E6DC8"
    medical: "#52B4E996"
    service: "#9FED5896"
    engineering: "#EFB34196"
    security: "#DE3A3A96"
    bar: "#79150096"
    science: "#D381C996"
    cargo: "#A4610696"
    neutral: "#D4D4D496"
    neutralLight: "#D4D4D428"
    expedition: "#00836E96"
``

**Comment by fedKotikeD** [comment]
> Contributor

Дак так в ПРе и есть
